### ISSUE TITLE
Filtering step

### ISSUE THREAD

**Issue by pabloacera** [GoekeLab/xpore#23]
Hi, 
Congrat for this great tool!
I have a doubt about the reason behind this statement in the preprint
 `we exclude positions where the distributions for the unmodified and modified signals are nearly identical`
I do not understand what this means. Is the tool filtering positions where there is 50% stoichiometry? 
Thanks!

**Comment by ploy-np** [comment]
Hi @pabloacera, Thank you for your question!

xpore infers two distributions from the signal data - one is assumed to be from modified RNAs and the other is assumed to be from unmodified RNAs. If these two distributions are close to each other, it implies that the signal data density should have only a single distribution - either from modified or unmodified RNAs. In other words, those positions are likely to be 100% unmodified (or 100% modified) for all conditions, that is, there is no difference in modification rates between conditions. Because we are interested in the positions that are differentially modified between conditions, we exclude them and test the differential modifications only on the remaining positions.

**Comment by pabloacera** [comment]
Hi @ploy-np 

Thanks a lot for your quick answer! I misinterpret te preprint information, makes a lot of sense.
Pablo.
